### ISSUE TITLE
No sound when taking picture

### ISSUE THREAD

**Issue by mjohn123** [roshanabhishek/Camera2api#1]
Thanks for a great job. I am using your code to take a picture. It takes the picture, but it makes no sound! I want the default click sound that Android makes. How can we do it in your code? Thanks

This is my solution now. I am not sure it is good or not because shutter maybe happens, but the picture may not take (i.e camera fails to write pictures folder-I tried to remove pictures folder on my phone and your code will crash, it is better to check/ create if the folder is not exist)

```
    public void takepicture(View view) {

        try {
            mImageFile = createImageFile();

        } catch (IOException e) {
            e.printStackTrace();
        }

        lockFocus();
        MediaActionSound sound = new MediaActionSound();
        sound.play(MediaActionSound.SHUTTER_CLICK);
    }
```

Besides, when you close the app, i think your thread is still close because it has warning

```
09-25 18:39:05.854 26068-26080/com.example.roshan.camera2api W/MessageQueue: Handler (android.os.Handler) {1ca4e949} sending message to a Handler on a dead thread
                                                                             java.lang.IllegalStateException: Handler (android.os.Handler) {1ca4e949} sending message to a Handler on a dead thread
                                                                                 at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
                                                                                 at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                                 at android.os.Handler.sendMessageAtFrontOfQueue(Handler.java:623)
                                                                                 at android.hardware.camera2.legacy.RequestThreadManager.quit(RequestThreadManager.java:941)
                                                                                 at android.hardware.camera2.legacy.LegacyCameraDevice.close(LegacyCameraDevice.java:444)
                                                                                 at android.hardware.camera2.legacy.LegacyCameraDevice.finalize(LegacyCameraDevice.java:468)
                                                                                 at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:194)
                                                                                 at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:177)
                                                                                 at java.lang.Thread.run(Thread.java:818)
```

**Comment by roshanabhishek** [comment]
Thanks for your contribution.Taking picture was just a feature of an app I implemented and these code was not furthur updated.
